### ISSUE TITLE
Add check for presence of dependencies in the public API

### ISSUE THREAD

**Issue by Enselic** [cargo-public-api/cargo-public-api#383]
When designing a public API, it is generally good to ensure there are no third party items in the public API surface. That way it is easier to guarantee long term public API stability, for example.

It would be useful to add a flag that makes `cargo public-api` exit with an error if it finds foreign/external items in the public API. Except for items that belong to libstd and similar.

Let's go with `cargo public-api --deny external-items` until we come up with something better.

The general idea comes from https://users.rust-lang.org/t/tool-to-check-if-any-dependencies-sneaked-into-my-public-api/89903.

**Comment by Emilgardis** [comment]
I think this would need a way to allow certain items, e.g I may want to have `http` items in my api surface, but not others

this should probably also take crate versions into account.

So maybe a config would be easiest, something like

```toml
[package.metadata.public-api]
disallow-external = true
[[package.metadata.public-api.allowed-externals]]
package = "http"
version = "~0.2.9" # or if emitted, same version as package named "http" in this Cargo.toml, for that target
items = [] # effectively all items, or maybe it should be it's own field
```
